Update maps to version 7
It should be pointed out that the maps are not actually openable in Atlas
due to the PMP files being corrupt (or something):
> ERROR: Failed to load map maps/scenarios/{map_name}.pmp: File_InvalidType